name: hair
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 1.3.0
  firebase_analytics: ^8.1.2
  firebase_auth: 1.4.1
  cloud_firestore: 2.2.2
  uuid:
  provider: ^5.0.0
  country_code_picker: 2.0.2
  google_sign_in: ^5.0.4
  flutter_login_facebook: ^1.0.0-nullsafety.1
  pin_code_fields: ^7.2.0
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  introduction_screen: ^2.1.0
  switcher_button: ^0.0.4
  flutter_neat_and_clean_calendar: ^0.2.2+10
  flutter_slidable: 0.6.0
  image_picker:
  image_cropper:
  top_snackbar_flutter: ^1.0.0
  firebase_storage:
  google_maps_flutter:
  geolocator:
  geocode:
  simple_speed_dial: ^0.1.3
  intl: ^0.17.0
  expandable: ^5.0.1
  material_floating_search_bar: ^0.3.6
  shimmer: ^2.0.0
  flutter_animated_button: ^2.0.0
  dotted_line: ^3.1.0
  razorpay_flutter: ^1.2.7
  firebase_messaging:
  flutter_local_notifications: ^9.1.2
  http: ^0.13.4
  pdf: ^3.1.0
  open_file: ^3.1.0
  path_provider: ^2.0.1
  location: ^4.2.0
  permission_handler: ^8.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  flutter_launcher_icons: ^0.9.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/hicon4.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/segimage.jpg
    - images/user.png
    - images/barber.png
    - images/signin.jpg
    - images/massage.png
    - images/groom.png
    - images/bridal.png
    - images/freelancer.png
    - images/salon.png
    - images/face_mask.png
    - images/sanitizer.png
    - images/sterilizer.png
    - images/temprature.png
    - images/appointement.png
    - images/music.png
    - images/online_pay.png
    - images/wifi.png
    - images/parking.png
    - images/ac.png
    - images/male.png
    - images/female.png
    - images/unisex.png
    - images/razor.png
    - images/cut.png
    - images/bottole.png
    - images/more.png
    - images/h_icon.png
    - images/sbarber.png
    - images/suser.png
    - images/google_icon.png
    - images/facebook_icon.png
    - images/login.jpg
    - images/image1.jpg
    - images/image2.jpg
    - images/image3.jpg
    - images/rupee.png
    - images/treatment_chair.png
    - images/chair.png
    - images/created.gif
    - images/hicon2.jpeg
    - images/hicon3.png
    - images/hair5.jpg
    - images/hicon4.png
    - images/groom.jpg
    - images/bridal.jpg
    - images/newhaircolor.png
    - images/newmassage.png
    - images/barber5.jpg
    - images/nhicon.png
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: playfair
      fonts:
        - asset: fonts/playfair.ttf
    - family: ubuntur
      fonts:
        - asset: fonts/ubuntu_regular.ttf
    - family: ubuntub
      fonts:
        - asset: fonts/ubuntu_bold.ttf
    - family: ubuntul
      fonts:
        - asset: fonts/ubuntu_light.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
